// src/App.jsx
import Router from './routes/Router';

function App() {
  return (
    <>
      <main className="max-w-4xl mx-auto py-8 px-4">
        <Router />
      </main>

      <footer className="max-w-4xl mx-auto py-8 px-4 border-t border-gray-200 mt-12">
        <p className="text-sm text-center">© 2025 Carl Angelo Maniangap. All rights reserved.</p>
      </footer>
    </>
  );
}

export default App;

// src/App.vue
<script setup>
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <main class="max-w-4xl mx-auto py-8 px-4">
    <RouterView />
  </main>

  <footer class="max-w-4xl mx-auto py-8 px-4 border-t border-gray-200 mt-12">
    <p class="text-sm text-center">© 2025 Carl Angelo Maniangap. All rights reserved.</p>
  </footer>
</template>
